(() => {
'use strict';
const DIMENSIONS = ['傲慢','嫉妒','暴怒','懒惰','贪婪','暴食','色欲','善良','真诚','勇敢','勤奋','担当','自律','宽容'];
const SINS = DIMENSIONS.slice(0,7), VIRTUES = DIMENSIONS.slice(7);
const QUESTIONS = [
['团队成果被看见时，我希望自己的贡献被明确提到，也愿意说明自己承担过的部分。','傲慢','担当',.35],['事情出现疏漏时，即使不全是我的责任，我也愿意先接手把问题推进到解决。','担当','勤奋',.35],['即使一项工作枯燥且迟迟没有反馈，我通常仍能按照原计划继续推进。','勤奋','懒惰',-.35],['面对困难或令人焦虑的任务时，我容易先去刷视频、吃东西或做别的轻松事情。','懒惰','暴食',.35],['遇到喜欢的食物、娱乐或消费体验时，即使已经超过计划，我仍可能继续一会儿。','暴食','自律',-.35],['我会为了长期保障限制当下的消费或冲动，并希望手里始终留有一定余量。','自律','贪婪',.35],['当机会或资源有限时，我会先确保自己不会吃亏，并留意别人最终得到了多少。','贪婪','嫉妒',.35],['当身边的人得到我也很想要的机会时，我很难完全不介意，但表面上可能不会表现出来。','嫉妒','善良',-.35],['别人犯错时，我通常会先了解原因，并在能力范围内帮助对方收拾局面。','善良','宽容',.35],['发生冲突时，我通常能够先听完对方的解释，再决定是否反击。','宽容','暴怒',-.35],['遭遇明显不公平时，即使可能引发冲突，我也倾向于立即站出来指出问题。','暴怒','勇敢',.35],['即使表达真实看法可能带来压力，我仍愿意在重要问题上说出自己的立场。','勇敢','真诚',.35],['在亲密关系中，我需要清晰、真实的回应，而不是长期依靠猜测维持安全感。','真诚','色欲',.35],['来自重要之人的欣赏、心动或选择，会明显增强我对自身价值的感受。','色欲','傲慢',.35],['在重要关系中，如果对方不再欣赏我，我会更想证明自己的能力或不可替代性。','傲慢','色欲',.35],['团队遇到麻烦时，我愿意站出来承担责任，也希望别人知道我确实接住了这件事。','担当','傲慢',.35],['即使事情并不有趣，只要它关系到承诺或重要结果，我通常会把它完成。','勤奋','担当',.35],['明知一件事很重要时，我仍可能因为害怕做不好或觉得太麻烦而迟迟不开始。','懒惰','勤奋',-.35],['情绪低落或疲惫时，我容易沉浸在娱乐、食物或购物中，并把原本要做的事继续推迟。','暴食','懒惰',.35],['即使某种体验非常愉快，当已经达到预先设定的时间或数量时，我通常能够停下来。','自律','暴食',-.35],['我习惯为金钱、时间和重要资源预留安全空间，并希望关键选择仍掌握在自己手里。','贪婪','自律',.35],['看到别人拥有更多资源、认可或更好的位置时，我容易感觉自己的份额显得不足。','嫉妒','贪婪',.35],['即使别人得到的是我也想要的机会，我通常仍能真心祝贺，并把注意力转回自己的行动。','善良','嫉妒',-.35],['别人令我失望后，只要对方愿意认真修复，我通常能够理解其局限并给出新的机会。','宽容','善良',.35],['被冒犯之后，我容易反复回想，并希望对方清楚感受到自己行为带来的代价。','暴怒','宽容',-.35],['当重要边界被突破时，即使需要承担冲突风险，我也会选择直接维护自己的立场。','勇敢','暴怒',.35],['在重要关系或合作中，我更愿意表达真实需要，而不是用沉默等待别人猜中。','真诚','勇敢',.35],['当我对一个人产生强烈好感时，我希望彼此能够明确回应、认真投入并建立真实承诺。','色欲','真诚',.35]
];
const MODES={傲慢:'确认自己的判断、能力和不可替代性',嫉妒:'通过差距与比较确认自身位置',暴怒:'在边界受触碰时快速建立防御',懒惰:'在压力和消耗中降低行动投入',贪婪:'通过掌握资源和选择权获得安全感',暴食:'通过即时体验补偿疲劳或情绪需要',色欲:'通过回应、吸引和亲密确认关系价值',善良:'把他人的感受和需要纳入自己的选择',真诚:'用清晰表达与一致行动减少猜测',勇敢:'即使存在风险仍向重要目标靠近',勤奋:'依靠持续行动把承诺转化为结果',担当:'在事情重要时主动接住责任',自律:'通过规则、边界和延迟满足维持方向',宽容:'为差异、失误和修复保留空间'};
const BEHAVIOR={傲慢:'自我确证',嫉妒:'价值比较',暴怒:'边界反击',懒惰:'压力回避',贪婪:'资源掌控',暴食:'即时补偿',色欲:'关系确认',善良:'关系照顾',真诚:'真实表达',勇敢:'迎难行动',勤奋:'稳定推进',担当:'主动承担',自律:'规则保持',宽容:'温和接纳'};
const TYPE=Object.fromEntries(DIMENSIONS.map(d=>[d,BEHAVIOR[d]+'型'+d]));
const PORTRAIT={傲慢:['自己的判断是否被轻视','能力与贡献得到承认','不被否定的自我价值'],嫉妒:['自己与他人的差距','仍可追赶的位置','不被比较抹去的价值'],暴怒:['边界是否被突破','尊严、公平与行动权','对事件的解释权'],懒惰:['任务带来的压力和消耗','当前精力与心理空间','不被任务完全占据的自由'],贪婪:['资源是否正在减少','安全余量与选择权','不受他人控制的底牌'],暴食:['当下最强烈的感受缺口','即刻恢复与愉快体验','暂时远离压力的空间'],色欲:['回应是否变淡或中断','自己是否仍被选择','真实而明确的亲密连接'],善良:['他人是否受到伤害','关系中的照顾与体面','不以伤害换取结果的原则'],真诚:['表达与事实是否一致','清晰、可信的沟通','不依靠猜测维持的关系'],勇敢:['哪个选择虽然困难但重要','行动机会与成长空间','面对恐惧仍可前进的自己'],勤奋:['哪个目标需要持续投入','计划、进度与承诺','能够实际完成的结果'],担当:['谁需要把事情真正接住','责任边界和最终结果','值得信任的行动记录'],自律:['哪种诱惑正在偏离目标','规则、节奏与长期方向','对自身选择的控制感'],宽容:['对方是否仍有修复可能','理解差异的空间','关系继续成长的可能性']};
const BASE={
傲慢:['你通常不急于证明自己，也容易承认不足；但有时可能低估自己的贡献。','你大多能接受不同意见，只有重要能力被质疑时才会明显维护自己。','你具备自我确信，也通常能听取不同意见，自信与开放大致平衡。','你重视判断与认可，能够展现担当，但被质疑时可能更难快速松动观点。','自我确证强烈影响你的决定，能力、判断和贡献是否被看见对你尤其重要。','稳定的自信不需要每次都证明自己正确，承认局限不会削弱价值。'],
嫉妒:['你较少通过比较确认价值，通常能按照自己的节奏看待得失。','你偶尔注意到差距，但比较通常不会持续主导情绪。','他人的进展既会带来动力，也可能暂时影响你对自身进度的评价。','你对机会、认可和位置差距较敏感，外界进展容易打乱自己的节奏。','价值比较是强烈驱动力，你会敏锐捕捉差距，并据此重新判断自身位置。','把比较当作信息，不要让局部差距成为对整体价值的裁决。'],
暴怒:['你较少通过愤怒处理冲突，但也要留意真实边界是否被压低。','愤怒主要在明显不公时出现，多数时候你能延迟反应。','你有保护边界的能力，也通常会为完整判断保留空间。','遭遇冒犯或不公时，你容易快速进入防御，反应可能先于判断出现。','边界反击强烈影响你的选择，愤怒很容易转化成即时行动能量。','情绪提示边界，但不必替你决定全部行动，先明确真正想获得的结果。'],
懒惰:['你通常能在缺乏兴趣时继续行动，但也要避免忽视真实疲劳。','你偶尔推迟困难任务，不过通常能在适当时间重新启动。','行动状态容易受到兴趣、压力和任务清晰度影响。','复杂、枯燥或可能失败的任务容易让你降低投入或延迟开始。','压力回避明显主导行动，缺乏反馈或路径不清时尤其难以启动。','不要等待完全准备好，把目标缩小为十分钟内能完成的下一个动作。'],
贪婪:['你较少依靠积累获得安全感，但可能低估长期保障的重要性。','你会关注资源，不过通常不会让“获得更多”成为持续目标。','你重视保障，也愿意分享，积累与放手大致保持平衡。','资源、机会和控制感对安全感很重要，“足够”的标准可能不断后移。','资源掌控强烈影响你的选择，即使已经拥有较多，你仍会优先注意不足和失去。','为积累设置明确目的和停止条件，让资源服务生活，而不是持续推迟满足感。'],
暴食:['你通常能控制即时诱惑，但也可能对正常享受和休息有所保留。','你偶尔通过愉快体验放松，多数时候能在适当位置停止。','疲惫、无聊或压力较高时，投入程度可能超过原计划。','食物、娱乐、购物或即时反馈较容易成为调节情绪的方式。','即时补偿强烈影响状态，具有快速反馈的体验容易吸引注意并变得难以停止。','先确认需要的是快乐、休息还是逃离，再选择真正能够恢复状态的方式。'],
色欲:['吸引、关注和亲密回应较少主导你的关系判断。','你会感受到亲密需要，但通常能兼顾边界和长期适配。','吸引、新鲜感与稳定性在关系判断中都有一定分量。','你对回应、亲密和被选择感较敏感，强烈连接可能暂时压过长期判断。','关系确认强烈影响你的选择，回应的温度与确定性会明显改变你的安全感。','吸引和回应是关系的一部分，也要给边界、稳定和共同承担同等判断权重。'],
善良:['你更倾向于就事论事，较少让他人感受改变自己的判断。','你会照顾他人，但通常只在不明显牺牲自身目标时这样做。','你能在个人需要与他人感受之间保持一定平衡。','你会主动考虑选择对他人的影响，并愿意为关系留下余地。','关系照顾强烈影响决定，你很难在明知会伤害他人的情况下只考虑自身利益。','善良不等于无限承担，照顾别人时也需要保护自己的边界和资源。'],
真诚:['你更看重情境效果，未必会把全部真实想法直接表达出来。','你会在安全和必要时表达真实，但仍会根据关系风险有所保留。','你通常希望表达与事实一致，也能理解适度保留的必要性。','你重视清晰、可信和一致的沟通，不愿长期停留在模糊猜测中。','真实表达强烈影响选择，你希望关系与合作经得起直接说明和实际验证。','真实不等于毫无过滤，选择合适时机和方式能让诚实更有建设性。'],
勇敢:['你更重视风险控制，通常会在确定性足够时才采取行动。','你会面对必要挑战，但很少主动选择高风险路径。','你能在风险与机会之间权衡，重要目标会提升行动意愿。','即使存在不确定，你仍愿意向重要目标靠近，不只停留在安全位置。','迎难行动强烈影响决定，越是重要且具有挑战的事情，越可能激发你的行动感。','勇敢不是忽视风险，提前准备退出条件能让行动更可持续。'],
勤奋:['你更依赖兴趣和即时反馈，持续投入本身不一定构成动力。','必要时你能推进任务，但长期枯燥投入较容易消耗状态。','你具备持续行动能力，投入程度会受到目标意义影响。','你愿意通过稳定行动换取长期结果，通常能够遵守重要计划。','稳定推进强烈影响你的选择，承诺一旦形成，你倾向于持续投入直到出现结果。','持续行动之外也要安排恢复，长期透支并不等同于真正勤奋。'],
担当:['你更重视明确责任边界，不会轻易接下不属于自己的问题。','责任清晰时你会完成任务，但较少主动扩大承担范围。','重要事情出现缺口时，你能在能力范围内接住责任。','你愿意主动推动问题解决，也重视自己能否成为值得信任的人。','主动承担强烈影响决定，越是关键时刻，你越容易把最终结果接到自己身上。','担当不等于代替所有人负责，明确谁应共同承担能够避免长期透支。'],
自律:['你更看重当下状态和灵活性，固定规则较难长期约束选择。','你能维持必要边界，但规则过于僵硬时容易失去动力。','你能在自由与约束之间保持基本平衡，并为重要目标限制部分冲动。','你重视规则、节奏和延迟满足，通常能为了长期方向管理当下选择。','规则保持强烈影响决定，你倾向于通过明确边界和自我要求维持控制感。','规则应服务目标，也要允许根据现实反馈调整，避免把自律变成僵化。'],
宽容:['你对原则和结果要求较清晰，失误发生后不容易快速放下。','你愿意理解原因，但是否继续接纳取决于对方是否真正修复。','你能在原则与理解之间保持平衡，既不轻易纵容也不急于否定。','你愿意为差异和失误保留修复空间，不轻易用单次行为定义完整的人。','温和接纳强烈影响决定，即使受过伤害，你仍倾向于寻找理解与重新连接的可能。','宽容不要求取消边界，理解一个人和继续接受同样的行为是两件事。']};
const STRENGTH=['这一倾向较少主导你的选择。','这一倾向会在部分情境中出现，但通常不是主要驱动力。','这一倾向对你的选择具有中等程度的影响。','这一倾向较为明显，尤其会在压力或不确定情境中增强。','这一倾向是你当前较强的心理驱动力之一。'];
const ANSWERS=['非常不符合','比较不符合','不确定／有时符合','比较符合','非常符合'];
const KEYS={progress:'svp_progress_v1',result:'svp_result_v1'};
let state={answers:Array(28).fill(null),times:Array(28).fill(null),modified:Array(28).fill(false),index:0,enteredAt:Date.now()}, autoTimer=null, currentResult=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function safeGet(k){try{return localStorage.getItem(k)}catch{return null}} function safeSet(k,v){try{localStorage.setItem(k,v)}catch{}} function safeRemove(k){try{localStorage.removeItem(k)}catch{}}
function view(id){$$('.view').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');scrollTo(0,0)}
function validAnswers(a){return Array.isArray(a)&&a.length===28&&a.every(x=>x===null||(Number.isInteger(x)&&x>=1&&x<=5))}
function restore(){const raw=safeGet(KEYS.progress);if(raw){try{const p=JSON.parse(raw);if(validAnswers(p.answers)){state={...state,...p,index:Math.max(0,Math.min(27,p.index||0)),enteredAt:Date.now()}}else throw 0}catch{safeRemove(KEYS.progress);toast('本地答题记录已损坏，请重新开始')}} const rr=safeGet(KEYS.result);if(rr){try{const x=JSON.parse(rr);if(x&&x.scores&&DIMENSIONS.every(d=>Number.isFinite(x.scores[d]))) currentResult=x}catch{safeRemove(KEYS.result)}} renderHome()}
function renderHome(){const has=state.answers.some(x=>x!==null), box=$('#homeActions');box.innerHTML=has?'<button class="btn primary" id="continueBtn">继续上次测试</button><button class="btn secondary" id="freshBtn">重新开始</button>':'<button class="btn primary" id="startBtn">开始测试</button>';$('#startBtn')?.addEventListener('click',start);$('#continueBtn')?.addEventListener('click',start);$('#freshBtn')?.addEventListener('click',()=>$('#confirmDialog').showModal());if(currentResult&&!has){box.insertAdjacentHTML('beforeend','<button class="btn secondary" id="lastResultBtn">查看上次结果</button>');$('#lastResultBtn').onclick=()=>showResult(currentResult)}}
function start(){view('quizView');renderQuestion()}
function recordTime(i){if(state.times[i]==null)state.times[i]=Math.max(1,Math.round((Date.now()-state.enteredAt)/1000))}
function saveProgress(){safeSet(KEYS.progress,JSON.stringify({answers:state.answers,times:state.times,modified:state.modified,index:state.index}))}
function renderQuestion(){clearTimeout(autoTimer);const i=state.index,q=QUESTIONS[i];$('#progressText').textContent=`${i+1} / 28`;$('#progressBar').style.width=`${(i+1)/28*100}%`;$('#questionIndex').textContent=`第 ${String(i+1).padStart(2,'0')} 题`;$('#questionText').textContent=q[0];$('#backBtn').style.visibility=i?'visible':'hidden';$('#answerList').innerHTML=ANSWERS.map((a,j)=>`<button class="answer ${state.answers[i]===j+1?'selected':''}" data-value="${j+1}"><span class="num">${j+1}</span><span>${a}</span></button>`).join('');$$('.answer').forEach(b=>b.onclick=()=>selectAnswer(+b.dataset.value,true));const chosen=state.answers[i]!=null;$('#nextBtn').disabled=!chosen;$('#nextBtn').textContent=i===27?'查看我的结果':'下一题';state.enteredAt=Date.now()}
function selectAnswer(v,auto){const i=state.index;if(state.answers[i]!=null&&state.answers[i]!==v)state.modified[i]=true;recordTime(i);state.answers[i]=v;saveProgress();$$('.answer').forEach((b,j)=>b.classList.toggle('selected',j===v-1));$('#nextBtn').disabled=false;if(auto&&i<27){clearTimeout(autoTimer);autoTimer=setTimeout(next,250)}}
function next(){if(state.answers[state.index]==null)return;if(state.index===27){finish();return}state.index++;saveProgress();renderQuestion()}
function back(){if(!state.index)return;recordTime(state.index);state.index--;saveProgress();renderQuestion()}
function level(s){return s<25?'倾向较弱':s<45?'偶尔显现':s<60?'中等倾向':s<75?'明显倾向':'强烈倾向'}
function band(s){return s<25?0:s<45?1:s<60?2:s<75?3:4}
function rank(scores,arr){return [...arr].sort((a,b)=>scores[b]-scores[a]||arr.indexOf(a)-arr.indexOf(b))}
function calculate(){const sums=Object.fromEntries(DIMENSIONS.map(d=>[d,0]));QUESTIONS.forEach((q,i)=>{const x=state.answers[i]-3;sums[q[1]]+=x;sums[q[2]]+=x*q[3]});const scores=Object.fromEntries(DIMENSIONS.map(d=>[d,Math.max(0,Math.min(100,Math.round(50+50*sums[d]/5.4)))]));const sins=rank(scores,SINS),virtues=rank(scores,VIRTUES);const max=Math.max(...DIMENSIONS.map(d=>scores[d]));let tied=DIMENSIONS.filter(d=>scores[d]===max);if(tied.length>1&&tied.length<14){const primarySum=d=>QUESTIONS.reduce((n,q,i)=>n+(q[1]===d?state.answers[i]-3:0),0), pm=Math.max(...tied.map(primarySum));tied=tied.filter(d=>primarySum(d)===pm)}const core=tied.length===14?[]:tied;const typeName=tied.length===14?'十四项力量相对均衡':core.length>1?`双核心类型：${core.map(d=>TYPE[d]).join(' × ')}`:TYPE[core[0]];const result={scores,sins,virtues,core,typeName,index:Math.round((scores[sins[0]]+scores[virtues[0]])/2),answers:[...state.answers],process:{times:[...state.times],modified:[...state.modified]},createdAt:Date.now()};return result}
function finish(){if(state.answers.some(x=>x==null)){toast('请先完成全部 28 道题');return}recordTime(27);view('loadingView');setTimeout(()=>{currentResult=calculate();safeSet(KEYS.result,JSON.stringify(currentResult));safeRemove(KEYS.progress);state.index=0;showResult(currentResult)},1000)}
function dimensionCopy(d,s){const b=band(s),trigger={傲慢:'当贡献、判断或能力受到质疑时',嫉妒:'当机会、认可或位置差距变得清晰时',暴怒:'当公平、尊严或边界受到触碰时',懒惰:'当任务复杂、枯燥或结果不确定时',贪婪:'当资源缩减或选择权可能旁落时',暴食:'当疲惫、无聊或情绪出现缺口时',色欲:'当亲密回应变慢、变淡或不够明确时',善良:'当他人的处境会被你的选择影响时',真诚:'当关系或合作陷入模糊猜测时',勇敢:'当重要目标伴随风险与压力时',勤奋:'当目标需要长期投入却缺少即时反馈时',担当:'当事情出现缺口、需要有人接住时',自律:'当即时诱惑与长期方向发生冲突时',宽容:'当失误、差异或伤害仍存在修复可能时'}[d];return `${STRENGTH[b]}${BASE[d][b]}${trigger}，这种反应真正想保护的是${PORTRAIT[d][2]}。${BASE[d][5]}`}
function topSubtitle(d){return `你以${BEHAVIOR[d]}回应世界，也在暗面与光面之间留下自己的选择。`}
function summary(r){const s=r.sins[0],v=r.virtues[0];return `你更容易以“${MODES[s]}”的方式处理压力与不确定，同时依靠“${MODES[v]}”修正自己的决定。前者说明你最敏感的需求，后者说明你愿意如何回应这种需求。`}
function layers(r){const groups=[['核心驱力','75–100，最容易直接主导重要选择。',75,101],['重要影响','60–74，在特定情境中显著增强。',60,75],['情境倾向','45–59，是否出现取决于压力和环境。',45,60],['低激活','0–44，目前较少直接主导选择。',0,45]];return `<div class="layer-grid">${groups.map(g=>{const ds=rank(r.scores,DIMENSIONS).filter(d=>r.scores[d]>=g[2]&&r.scores[d]<g[3]);return `<div class="layer"><h3>${g[0]}</h3><p>${g[1]}</p><div class="tags">${ds.length?ds.map(d=>`<span class="tag">${d} ${r.scores[d]}</span>`).join(''):'<span class="tag">暂无</span>'}</div></div>`}).join('')}</div>`}
function triggers(r){const defs=[['关系与亲密',['色欲','嫉妒','真诚','善良','宽容'],'亲密回应、比较、表达与修复相关模式被调用的程度。'],['冲突与边界',['暴怒','勇敢','宽容','担当'],'面对冲突时，边界反应、行动勇气与修复空间共同被调用的程度。'],['任务与行动',['懒惰','勤奋','自律','担当'],'压力回避的激活与持续推进、自我约束、主动承担等应对资源共同作用的程度。'],['资源与不确定',['贪婪','嫉妒','自律','暴食'],'资源安全、位置比较、规则保持与即时补偿相关模式被调用的程度。']];return defs.map(x=>{const s=Math.round(x[1].reduce((n,d)=>n+r.scores[d],0)/x[1].length);return `<div class="trigger-row"><h3>${x[0]}</h3><div class="bar neutral"><i style="width:${s}%"></i></div><div class="trigger-score">${s}</div><p>${x[2]}当前为“${level(s)}”；分数表示相关模式在该情境中被调用的程度，不代表能力高低。</p></div>`}).join('')}
function dimRows(r,arr,kind){return rank(r.scores,arr).map((d,i)=>{const s=r.scores[d];return `<article class="dimension-row"><div class="dimension-top"><div><div class="dim-meta">${kind} · 组内第 ${i+1} 位</div><div class="dim-name">${d}<small>${BEHAVIOR[d]}</small></div></div><div class="dim-score ${kind==='暗面驱力'?'sin-text':'virtue-text'}">${s}<small>${level(s)}</small></div></div><div class="bar ${kind==='暗面驱力'?'sin':'virtue'}"><i style="width:${s}%"></i></div><p class="dim-copy">${dimensionCopy(d,s)}</p></article>`}).join('')}
function synergy(r){const s=r.scores[r.sins[0]],v=r.scores[r.virtues[0]];let name,copy;if(s>=70&&v>=70){name='双高协同型';copy=['你的需要识别很快，修正与建设的力量也足，清楚目标时往往能把敏感转成行动。','压力突然上升时，保护动作仍可能先于解释出现，之后才由光面力量接管。','先说清真正要保护的东西，再让光面力量选择方式，敏锐就不必变成消耗。']}else if(s>=70){name='高驱力待调节型';copy=['环境稳定时，你能直接捕捉需要并快速建立保护，行动有明确方向。','高压下保护动作更容易先行，留给核对事实与调整方式的空间会缩小。','在反应与行动之间增加一次确认，让已有的光面力量更早进入选择。']}else if(v>=70){name='光面主导型';copy=['你更常用建设性方式处理需要，愿意顾及结果、关系或长期方向。','压力下暗面并未消失，只是可能以较隐蔽的回避、比较或控制感浮现。','承认真实需要而不急着否定它，光面选择会更扎实，也更少变成自我要求。']}else{name='情境平衡型';copy=['没有单一力量持续接管选择，你更容易依据眼前的人、事与风险调整方式。','压力增大时，反应会受具体触发点影响，表现可能比平时更摇摆。','找到当下最敏感的需要，再选择要调用的力量，比追求固定答案更有效。']}return `<div class="synergy-name">${name}</div><div class="synergy-grid">${['顺畅状态','压力状态','关键转折'].map((x,i)=>`<div><h3>${x}</h3><p>${copy[i]}</p></div>`).join('')}</div>`}
function insight(r){const sr=r.sins,vr=r.virtues,low=vr[vr.length-1],times=r.process?.times?.filter(Number.isFinite)||[],mods=r.process?.modified||[];const diffs=DIMENSIONS.map(d=>{const ix=QUESTIONS.map((q,i)=>q[1]===d?i:-1).filter(i=>i>=0);return Math.abs(r.answers[ix[0]]-r.answers[ix[1]])});const avgDiff=diffs.reduce((a,b)=>a+b,0)/diffs.length,extreme=r.answers.filter(x=>x===1||x===5).length/28,mid=r.answers.filter(x=>x===3).length/28;let process='';if(avgDiff<=.65)process+='同类情境里的选择大多方向一致，说明这些判断在不同表述下仍较稳定；';else if(avgDiff>=1.5)process+='同一主题在不同情境里的回答差异不小，说明你的反应很看具体关系与压力，而不是固定标签；';if(extreme>=.5)process+='你使用两端选项较多，表达取向时相当明确；';else if(mid>=.42)process+='你较常保留中间位置，许多选择需要看具体条件才会落定；';if(times.length===28){const mx=Math.max(...times),idx=times.indexOf(mx);if(mx>=Math.max(12,times.reduce((a,b)=>a+b,0)/times.length*1.8))process+=`你在第 ${idx+1} 题停留得更久，至少说明那一刻你给了这个情境更多权衡；`}const mc=mods.filter(Boolean).length;if(mc)process+=`你修改过 ${mc} 道答案，这里只把它看作重新权衡，而不是犹豫。`;const gap=r.scores[vr[0]]-r.scores[low];return `你的核心暗面驱力是<em>${sr[0]}</em>，它常在${PORTRAIT[sr[0]][0]}的场景里先出现；<em>${sr[1]}</em>和<em>${sr[2]}</em>也会把注意推向${PORTRAIT[sr[1]][1]}与${PORTRAIT[sr[2]][2]}，让保护反应变得更快。好在<em>${vr[0]}</em>并不是旁观者，它会带着<em>${vr[1]}</em>和<em>${vr[2]}</em>把冲动重新放回关系、事实与长期结果里。${gap>=20?`相较之下，${low}是目前较少被你调用的力量，真正容易卡住的不是看不见问题，而是在需要${MODES[low]}时缺少顺手的动作。`:`几项光面力量差距不大，你的卡点更可能是压力来得太快，修正动作晚了半步。`}${process}你真正需要练习的，是在最熟悉的保护动作出现时，先说清自己究竟在怕失去什么，再决定下一步。`}
function section(n,title,body,cls=''){return `<section class="report-section ${cls}"><div class="section-head"><span class="section-num">${n}</span><div><span class="section-kicker">结果报告</span><h2>${title}</h2></div></div>${body}</section>`}
function showResult(r){currentResult=r;const core=r.core[0]||r.sins[0],p=PORTRAIT[core];$('#resultContent').innerHTML=`<div class="result-wrap"><section class="hero-result panel-ornate"><div><span class="type-label">你的综合类型</span><h1>${r.typeName}</h1><div class="type-sub">${topSubtitle(core)}</div><p class="summary">${summary(r)}</p></div><div class="score-side"><div class="index-ring"><div><strong>${r.index}</strong><small>综合印记指数</small></div></div><div class="top-scores"><div>首要暗面<b class="sin-text">${r.sins[0]} ${r.scores[r.sins[0]]}</b></div><div>首要光面<b class="virtue-text">${r.virtues[0]} ${r.scores[r.virtues[0]]}</b></div><div>第二暗面　${r.sins[1]}</div><div>第二光面　${r.virtues[1]}</div></div></div></section>${section('', '七宗罪 × 七美德 14 维图谱',`<div class="chart-panel panel-ornate"><div class="chart-tabs"><button class="active" data-chart="all">综合图谱</button><button data-chart="sin">仅七宗罪</button><button data-chart="virtue">仅七美德</button></div><div class="chart-wrap"><canvas id="radar" role="img" aria-label="十四维分数图谱"></canvas></div><p class="chart-a11y">图表文字说明：${DIMENSIONS.map(d=>d+r.scores[d]+'分').join('；')}。红色表示七宗罪，金色表示七美德。</p></div>`)}${section('01','驱动力层级',layers(r))}${section('02','决策画像',`<div class="portrait-grid">${['你最先察觉','你首先保护','你最终保留'].map((x,i)=>`<div class="portrait-item"><span class="n">0${i+1}</span><label>${x}</label><p>${p[i]}</p></div>`).join('')}</div>`)}${section('03','情境触发地图',triggers(r))}${section('04','七宗罪维度明细',dimRows(r,SINS,'暗面驱力'))}${section('05','七美德维度明细',dimRows(r,VIRTUES,'光面力量'))}${section('06','暗面与光面协同',synergy(r))}${section('07','洞察总结',`<p class="insight">${insight(r)}</p>`)}</div>`;view('resultView');bindChart(r);requestAnimationFrame(()=>drawRadar(r,'all'))}
function bindChart(r){$$('[data-chart]').forEach(b=>b.onclick=()=>{$$('[data-chart]').forEach(x=>x.classList.remove('active'));b.classList.add('active');drawRadar(r,b.dataset.chart)})}
function drawRadar(r,mode){const c=$('#radar');if(!c)return;const rect=c.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);c.width=rect.width*dpr;c.height=rect.height*dpr;const x=c.getContext('2d');x.scale(dpr,dpr);const W=rect.width,H=rect.height,cx=W/2,cy=H/2,R=Math.min(W,H)*.34;x.clearRect(0,0,W,H);const drawGrid=n=>{for(const pct of [.25,.5,.75,1]){x.beginPath();for(let i=0;i<n;i++){const a=-Math.PI/2+i*Math.PI*2/n,px=cx+Math.cos(a)*R*pct,py=cy+Math.sin(a)*R*pct;i?x.lineTo(px,py):x.moveTo(px,py)}x.closePath();x.strokeStyle='rgba(185,149,85,.18)';x.stroke()}for(let i=0;i<n;i++){const a=-Math.PI/2+i*Math.PI*2/n;x.beginPath();x.moveTo(cx,cy);x.lineTo(cx+Math.cos(a)*R,cy+Math.sin(a)*R);x.strokeStyle='rgba(185,149,85,.13)';x.stroke()}};const poly=(arr,color,fill)=>{x.beginPath();arr.forEach((d,i)=>{const a=-Math.PI/2+i*Math.PI*2/arr.length,rr=R*r.scores[d]/100,px=cx+Math.cos(a)*rr,py=cy+Math.sin(a)*rr;i?x.lineTo(px,py):x.moveTo(px,py)});x.closePath();x.fillStyle=fill;x.fill();x.strokeStyle=color;x.lineWidth=1.7;x.stroke();arr.forEach((d,i)=>{const a=-Math.PI/2+i*Math.PI*2/arr.length,rr=R*r.scores[d]/100;x.beginPath();x.arc(cx+Math.cos(a)*rr,cy+Math.sin(a)*rr,d===r.sins[0]||d===r.virtues[0]?5:3,0,Math.PI*2);x.fillStyle=color;x.fill()})};const labels=arr=>arr.forEach((d,i)=>{const a=-Math.PI/2+i*Math.PI*2/arr.length,lr=R+34,px=cx+Math.cos(a)*lr,py=cy+Math.sin(a)*lr;x.textAlign=Math.cos(a)>.25?'left':Math.cos(a)<-.25?'right':'center';x.fillStyle=SINS.includes(d)?'#d27a83':'#d8bb79';x.font='15px sans-serif';x.fillText(d,px,py-3);x.fillStyle=SINS.includes(d)?'#b23a48':'#b99555';x.font='bold 19px serif';x.fillText(r.scores[d],px,py+18)});if(mode==='all'){drawGrid(14);poly(SINS,'#b23a48','rgba(143,38,53,.2)');poly(VIRTUES,'#d8bb79','rgba(185,149,85,.18)');x.beginPath();x.moveTo(cx,cy-R-12);x.lineTo(cx,cy+R+12);x.strokeStyle='rgba(216,187,121,.45)';x.stroke();labels(DIMENSIONS)}else{const arr=mode==='sin'?SINS:VIRTUES;drawGrid(7);poly(arr,mode==='sin'?'#b23a48':'#d8bb79',mode==='sin'?'rgba(143,38,53,.23)':'rgba(185,149,85,.2)');labels(arr)}}
function wrapText(ctx,text,x,y,max,line){let s='',yy=y;for(const ch of text.replace(/<[^>]+>/g,'')){const t=s+ch;if(ctx.measureText(t).width>max){ctx.fillText(s,x,yy);s=ch;yy+=line}else s=t}if(s)ctx.fillText(s,x,yy);return yy}
function saveImage(){if(!currentResult)return;try{const r=currentResult,c=document.createElement('canvas');c.width=900;c.height=1560;const x=c.getContext('2d');x.fillStyle='#080706';x.fillRect(0,0,c.width,c.height);const g=x.createRadialGradient(450,0,0,450,0,700);g.addColorStop(0,'#25130f');g.addColorStop(1,'#080706');x.fillStyle=g;x.fillRect(0,0,900,1560);x.strokeStyle='rgba(216,187,121,.35)';x.strokeRect(34,34,832,1492);x.strokeStyle='rgba(216,187,121,.12)';x.strokeRect(46,46,808,1468);x.textAlign='center';x.fillStyle='#b99555';x.font='24px serif';x.fillText('七宗罪 × 七美德综合测试',450,105);x.fillStyle='#eee4d5';x.font='bold 48px serif';wrapText(x,r.typeName,450,178,730,58);x.fillStyle='#d8bb79';x.font='22px sans-serif';x.fillText('综合印记指数',450,285);x.fillStyle='#eee4d5';x.font='bold 76px serif';x.fillText(r.index,450,365);x.strokeStyle='#b99555';x.beginPath();x.arc(450,335,78,0,Math.PI*2);x.stroke();x.textAlign='left';x.font='25px sans-serif';x.fillStyle='#cf6671';x.fillText(`首要暗面　${r.sins[0]} ${r.scores[r.sins[0]]}`,110,470);x.fillStyle='#d8bb79';x.fillText(`首要光面　${r.virtues[0]} ${r.scores[r.virtues[0]]}`,520,470);x.textAlign='center';x.fillStyle='#b2a99d';x.font='20px sans-serif';wrapText(x,summary(r),450,535,700,36);let y=670;x.fillStyle='#b99555';x.font='22px serif';x.fillText('十四维选择印记',450,y);y+=50;DIMENSIONS.forEach((d,i)=>{const col=i<7?0:1,row=i%7,xx=col?490:90,yy=y+row*64;x.textAlign='left';x.fillStyle=SINS.includes(d)?'#cf6671':'#d8bb79';x.font='20px sans-serif';x.fillText(d,xx,yy);x.fillStyle='#211a16';x.fillRect(xx+70,yy-14,220,8);x.fillStyle=SINS.includes(d)?'#9f3040':'#b99555';x.fillRect(xx+70,yy-14,220*r.scores[d]/100,8);x.textAlign='right';x.fillStyle='#eee4d5';x.fillText(r.scores[d],xx+330,yy)});y=1185;x.textAlign='center';x.fillStyle='#b99555';x.font='22px serif';x.fillText('洞察摘要',450,y);x.fillStyle='#c6bdb1';x.font='19px sans-serif';const plain=insight(r).replace(/<[^>]+>/g,'').slice(0,260)+'…';wrapText(x,plain,450,y+46,700,33);x.fillStyle='#746d65';x.font='16px sans-serif';x.fillText('结果仅供娱乐与自我观察，不能替代专业判断。',450,1490);const url=c.toDataURL('image/png');const a=document.createElement('a');a.href=url;a.download='七宗罪与七美德综合测试结果.png';document.body.appendChild(a);a.click();a.remove();$('#resultImage').src=url;setTimeout(()=>$('#imageDialog').showModal(),300)}catch{toast('图片下载失败，请稍后重试')}}
function resetAll(){safeRemove(KEYS.progress);safeRemove(KEYS.result);state={answers:Array(28).fill(null),times:Array(28).fill(null),modified:Array(28).fill(false),index:0,enteredAt:Date.now()};currentResult=null;$('#confirmDialog').close();renderHome();view('homeView')}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}
$('#backBtn').onclick=back;$('#nextBtn').onclick=next;$('#saveBtn').onclick=saveImage;$('#restartBtn').onclick=()=>$('#confirmDialog').showModal();$('#cancelReset').onclick=()=>$('#confirmDialog').close();$('#confirmReset').onclick=resetAll;$('#closeImage').onclick=()=>$('#imageDialog').close();addEventListener('keydown',e=>{if($('#quizView').classList.contains('active')&&/^[1-5]$/.test(e.key))selectAnswer(+e.key,true)});addEventListener('resize',()=>{if($('#radar')&&currentResult){const m=$('[data-chart].active')?.dataset.chart||'all';drawRadar(currentResult,m)}});restore();
})();
